extern PARTS_RECT logo_rect[];					//ロゴ
extern PARTS_RECT mouse_ui_rect[];				//マウスの矩形
extern PARTS_RECT hand_ui_rect[];				//手の矩形
extern PARTS_RECT object_icon_rect[];			//オブジェクトのアイコン
extern PARTS_RECT shot_ui_rect[];				//攻撃の説明
extern PARTS_RECT catch_font_rect[];			//手の説明
extern PARTS_RECT move_ment_font_rect[];		//移動キーがのアイコン
extern PARTS_RECT arrow_rect[];					//移動の説明で使う矢印
extern PARTS_RECT main_bill_rect[];				//メインビル
extern PARTS_RECT hp_bar_rect[];				//HPバーの矩形
extern PARTS_RECT game_goal_rect[];				//クリア条件の文字
extern PARTS_RECT title_proposal_rect[];		//タイトルでゲームへのスタート条件を説明
extern PARTS_RECT number_rect[];				//数字の矩形
extern PARTS_RECT clear_rect[];					//クリア文字の矩形